version: "3.8"
services:

    www:
        build: php
        container_name: www_php_ssmtp
        restart: always
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./project:/var/www/project
            - ./php/ssmtp/ssmtp.conf.local:/etc/ssmtp/ssmtp.conf
            - ./php/ssmtp/revaliases.local:/etc/ssmtp/revaliases
        labels:
            - "traefik.enable=true"
            # http
            - "traefik.http.routers.http_mailssmtp.rule=Host(`mailssmtp.test`)"
            - "traefik.http.routers.http_mailssmtp.entrypoints=http"
        networks:
            - traefik #add 1st so traefik performs better
            - dev
        # ports:
        #   - "8741:80"

networks:
    dev:
    traefik:
        name: traefik_global